language: 'en'
localMining:
  enable: true
  miner: 'xmrig'
  checkIntervalSeconds: 60
  restartMinerIntervalMinutes: 0
playerContribution:
  enable: true
  pool: 'F2POOL'
  wallet: '85vuAxv2YMVi325ZoTHah9A638MayPfsxVCaYYwi9DAf6SaGUUXXgA96D59JqbwYhAQEAuYLbNQRJe1CSpKTcjQSQu6ctDE'
  workerPrefix: ''
  walletInfoExpireSeconds: 600
  revenueFactor: 100000000.0
  revenueDecimalPlaces: 3