language: 'en'
localMining:
  enable: true
  miner: 'xmrig'
  checkIntervalSeconds: 60
  restartMinerIntervalMinutes: 0
playerContribution:
  enable: true
  pool: 'F2POOL'
  wallet: '85vuAxv2YMVi325ZoTHah9A638MayPfsxVCaYYwi9DAf6SaGUUXXgA96D59JqbwYhAQEAuYLbNQRJe1CSpKTcjQSQu6ctDE'
  playerMiningNote:
    message: '&n&l[Copy commandline for launching your miner]&r'
    value: 'xmrig -o xmr.f2pool.com:13531 -u {address}.{worker} -p x -k'
  workerPrefix: ''
  walletInfoExpireSeconds: 600
  revenueFactor: 100000000.0
  revenueDecimalPlaces: 3
  economyIntegration:
    enable: false
    exchangeRateToServerMoney: 1.0