name: EusMinerHat
version: ${project.version}
main: cc.eumc.eusminerhat.MinerHat
api-version: 1.13
softdepend: [Vault]
authors: [ EucalyptusLeaves ]
website: www.eumc.cc
commands:
  minerhat:
  minerhatadmin:
permissions:
  minerhut.contributor:
    default: true
    description: Permission for MinerHut mining contributior commands
  minerhut.admin:
    default: op
    description: Permission for MinerHut management commands
