name: EusMinerHat
version: ${project.version}
main: cc.eumc.eusminerhat.MinerHat
api-version: 1.13
softdepend: [Vault]
authors: [ EucalyptusLeaves ]
website: www.eumc.cc
commands:
  minerhat:
  minerhatadmin:
permissions:
  minerhat.contributor:
    default: true
    description: Permission for MinerHat mining contributior commands
  minerhat.admin:
    default: op
    description: Permission for MinerHat management commands
